name: .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest  # Windows is required for .NET Framework

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '4.8'  # .NET Framework version (adjust if needed)

    - name: Restore dependencies
      run: nuget restore Part1.sln  # Restores packages for .NET Framework

    - name: Build
      run: msbuild Part1.sln /p:Configuration=Debug  # Uses Debug config

    - name: Test
      run: dotnet test --no-build --verbosity normal  # Runs your tests
